### ISSUE TITLE
Grails 3.0.9 with 3.0.0.M1 - NoCacheRegionFactoryAvailableException

### ISSUE THREAD

**Issue by felansu** [grails-plugins/grails-spring-security-core#390]
I'm using grails 3.0.9 wih spring-security-core:3.0.0.M1.

Learning the oficial tutorial [here](https://grails-plugins.github.io/grails-spring-security-core/guide/tutorials.html) get the follow error:
```
Caused by: org.hibernate.cache.NoCacheRegionFactoryAvailableException: Second-level cache is used in the application, but property hibernate.cache.region.factory_class is not given; please either disable second level cache or set correct region factory using the hibernate.cache.region.factory_class setting and make sure the second level cache provider (hibernate-infinispan, e.g.) is available on the classpath.
        at org.hibernate.cache.internal.NoCachingRegionFactory.buildEntityRegion(NoCachingRegionFactory.java:83)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:364)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
        at org.grails.orm.hibernate.cfg.GrailsAnnotationConfiguration.buildSessionFactory(GrailsAnnotationConfiguration.java:407)
        at org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.doBuildSessionFactory(ConfigurableLocalSessionFactoryBean.java:479)
        at org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.buildSessionFactory(ConfigurableLocalSessionFactoryBean.java:473)
        at org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean.afterPropertiesSet(ConfigurableLocalSessionFactoryBean.java:387)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
        ... 40 more
```

I'm trying this in *application.yml*:
```
    hibernate:
        cache:
            queries: false
            use_second_level_cache: false
            use_query_cache: false
```

and this in *application.groovy*:
```
grails.plugin.springsecurity.hibernate.cache.queries = false
grails.plugin.springsecurity.hibernate.cache.useSecondLevelCache = false
```

but get the same error

Its a bug ?  How can solve this ? Thanks !

**Comment by felansu** [comment]
Sorry.... i'm completly stupid...

I'm trying set the hibernate configuration in the grails level:
```
grails:
    mime:
      ...
    hibernate:
        cache:
            queries: false
            use_second_level_cache: false
            use_query_cache: false
```

this is the correct:
```
grails:
    mime:
        ...
    hibernate:
        cache:
            queries: false
    views:
       ....
hibernate:
    cache:
        use_second_level_cache: false
        use_query_cache: false
```
