### ISSUE TITLE
exception on startup with spring-boot-1.3.1

### ISSUE THREAD

**Issue by zyro23** [grails-plugins/grails-spring-security-core#401]
https://github.com/spring-projects/spring-boot/commit/007ec9e46be147403bd2ad85580d0a23eb41dc15 fixing spring-projects/spring-boot#4525 makes `SecurityFilterAutoConfiguration` load `SecurityProperties` which depends on `spring-security-config`.

result without `spring-security-config` on the classpath is a `ClassDefNotFound` on startup with grails-3.1.0.rc1 (spring-boot-1.3.1)

workaround: `@EnableAutoConfiguration(exclude = [SecurityFilterAutoConfiguration])`

looking at `SecurityFilterAutoConfiguration` i think it should be ok to only load it conditionally when `spring-security-config` is present, just like `SecurityAutoConfiguration` does with `@ConditionalOnClass({ AuthenticationManager.class,	GlobalAuthenticationConfigurerAdapter.class })`?
then, this would be a boot issue...

**Comment by hakanernam** [comment]
Workaround seems to ok. I have not yet seen any problems after adding the annotation.

**Comment by hakanernam** [comment]
If I run he program with grails console, stop it and try to run it again, the problem resurfaces: with spring security core configuration being attempted twice second time around:

(A newly created (3.1.0.RC1) app w/o security does not show this behavior, so It seems to be related to spring-security)

```
grails> run-app
| Running application...
objc[9194]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Grails application running at http://localhost:8080 in environment: development

grails> stop-app
| Shutting down application...
| Application shutdown.

grails> run-app
| Running application...
grails> objc[9606]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
objc[9607]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

^^^^^^^Note the duplication above^^^

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Configuring Spring Security Core ...
... finished configuring Spring Security Core

ERROR grails.boot.GrailsApp - Application startup failed
```

Stacktrace:

```
ERROR grails.boot.GrailsApp - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityProperties' defined in class path resource [org/springframework/boot/autoconfigure/security/SecurityFilterAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.SecurityProperties]: Factory method 'securityProperties' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:51) [grails-core-3.1.0.RC1.jar:3.1.0.RC1]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:335) [grails-core-3.1.0.RC1.jar:3.1.0.RC1]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:324) [grails-core-3.1.0.RC1.jar:3.1.0.RC1]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-3.1.0.RC1.jar:3.1.0.RC1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.5.jar:2.4.5]
	at appbase.Application.main(Application.groovy:8) [main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.security.SecurityProperties]: Factory method 'securityProperties' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 23 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/security/config/http/SessionCreationPolicy
	at org.springframework.boot.autoconfigure.security.SecurityProperties.<init>(SecurityProperties.java:88) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration.securityProperties(SecurityFilterAutoConfiguration.java:72) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration$$EnhancerBySpringCGLIB$$223b7060.CGLIB$securityProperties$0(<generated>) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration$$EnhancerBySpringCGLIB$$223b7060$$FastClassBySpringCGLIB$$b13a9f2e.invoke(<generated>) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration$$EnhancerBySpringCGLIB$$223b7060.securityProperties(<generated>) ~[spring-boot-autoconfigure-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) ~[springloaded-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.security.config.http.SessionCreationPolicy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_66]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
	... 37 common frames omitted
WARN grails.boot.GrailsApp - Error handling failed (Error creating bean with name 'securityEventListener': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.config.internalCacheAdvisor': Cannot resolve reference to bean 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0' while setting bean property 'cacheOperationSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.AnnotationCacheOperationSource#0': Cannot resolve reference to bean 'grailsApplication' while setting bean property 'grailsApplication'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'grailsApplication' is defined)

FAILURE: Build failed with an exception.
```

**Comment by dmahapatro** [comment]
Adding the workaround here fore reference:

    Note: Use @EnableAutoConfiguration from Spring instead of the Grails internal

```groovy
import grails.boot.GrailsApp
import grails.boot.config.GrailsAutoConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration

@EnableAutoConfiguration(exclude = [SecurityFilterAutoConfiguration])
class Application extends GrailsAutoConfiguration {
    static void main(String[] args) {
        GrailsApp.run(Application, args)
    }
}
```

**Comment by orubel** [comment]
This works but there is still an issue when bootstrapping. Will create new ticket.

**Comment by burtbeckwith** [comment]
Fixed in 3.0.1

**Comment by bhushan154** [comment]
Same issue with 3.1.1.
Need to add the below line but not mentioned anywhere is the documentation
@EnableAutoConfiguration(exclude = [SecurityFilterAutoConfiguration])

**Comment by PiotrZakrzewski** [comment]
I have also encountered the same issue in a fresh Grails 3.2.5 Grails app with security core 3.1.1

**Comment by emmanuj** [comment]
Seeing this with a fresh grails 3.3.8 app
