### ISSUE TITLE
Filter order incorrect: .IllegalStateException: There was a problem retrieving the current GrailsWebRequest

### ISSUE THREAD

**Issue by jblamber** [grails-plugins/grails-spring-security-core#412]
Hi folks, using spring-security-core:3.0.3 and grails 3.1.0 - whenever I do a force refresh (cntrl+f5) I get a stacktrace vomit from grails (see below). The rest of my grails app has view overrides for the login pages, and one scaffolded class. Since I can't modify web.xml in grails 3 - how can I correct the filter ordering issue? 

    Grails application running at http://localhost:8080 in environment: development
    ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet grailsDispatcherServlet threw exception
    java.lang.IllegalStateException: There was a problem retrieving the current GrailsWebRequest. This usually indicates a filter ordering issue (the 'springSecurityFilterChain' filter-mapping element must be positioned after the 'grailsWebRequest' element when using @Secured annotations).
        at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.determineUrl(AnnotationFilterInvocationDefinition.groovy:90) ~[spring-security-core-3.0.3.jar:na]
        at grails.plugin.springsecurity.web.access.intercept.AbstractFilterInvocationDefinition.getAttributes(AbstractFilterInvocationDefinition.groovy:72) ~[spring-security-core-3.0.3.jar:na]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:196) ~[spring-security-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53) ~[spring-security-c.3.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:149) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]

        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62) ~[spring-security-core-3.0.3.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.a.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:719) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:390) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:317) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:445) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:304) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:181) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$WorkerreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
    ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=404, location=/error]
    java.lang.IllegalStateException: There was a problem retrieving the current GrailsWebRequest. This usually indicates a filter ordering issue (the 'springSecurityFilterChain' filter-mapping element must be positioned after the 'grailsWebRequest' element when using @Secured annotations).
        at grails.plugin.springsecurity.web.access.intercept.AnnotationFilterInvocationDefinition.determineUrl(AnnotationFilterInvocationDefinition.groovy:90) ~[spring-security-core-3.0.3.jar:na]
        at grails.plugin.springsecurity.web.access.intercept.AbstractFilterInvocationDefinition.getAttributes(AbstractFilterInvocationDefinition.groovy:72) ~[spring-security-core-3.0.3.jar:na]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:196) ~[spring-security-core-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:123) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4LEASE.jar:4.0.3.RELEASE]
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53) ~[spring-security-core-3.0.3.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:149) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]

        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62) ~[spring-security-core-3.0.3.jar:na]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) ~[spring-security-web-4.0.3.RELEASE.jar:4.0.3.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) ~[spring-security-web-4.0ASE.jar:4.0.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:719) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:390) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:317) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:445) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:304) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:181) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:14mcat-embed-core-8.0.30.jar:8.0.30]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar:8.0.30]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by chrismalan** [comment]
I get exactly the same, also with spring-security-core:3.0.3 and grails 3.1.0.  Despite that the application keeps on working.  I'd be very interested in a solution to this.

**Comment by burtbeckwith** [comment]
It's complaining about `errorCode=404, location=/error` - did you remove the url mapping for code 404 (`"404"(view:'/notFound')` ?

**Comment by chrismalan** [comment]
Hi Burt,
      
      This was my UrlMappings.groovy:
      class UrlMappings { 
          static mappings = {
              "/$controller/$action?/$id?(.$format)?"{
                  constraints {
                      // apply constraints here
                  }
              }
      
           //"/"(view:"/index")
      
          "/"(controller:"home")
           "500"(view:'/error') 
          "404"(view:'/notFound') }
      
      }
      -----------------------------------
      I changed it to:
      class UrlMappings {
      
          static mappings = {
              "/$controller/$action?/$id?(.$format)?"{
                  constraints {
                      // apply constraints here
                  }
              }
                                                  ** commented out entry
      removed
              "/"(view:'/home/index')  ** change
              "500"(view:'/error')
              "404"(view:'/notFound')
          }
      }
      ----------------------------------
      Now everything is fine.
      
      The problem persisted even after I removed //"/"(view:"/index")
      .  It did map correctly to /home/index, though, as it always did. 
      Only after changing the "/" mapping to "/"(view:'/home/index') did
      the problem go away.
      
      On another note, grails install-templates only copies three files
      over:
      Copied AsyncController.groovy to location
/home/chris/Work/projects/grails/g3demo/src/main/templates/scaffolding/AsyncController.groovy
      | Copied AsyncSpec.groovy to location
/home/chris/Work/projects/grails/g3demo/src/main/templates/scaffolding/AsyncSpec.groovy
      | Copied ScaffoldedController.groovy to location
/home/chris/Work/projects/grails/g3demo/src/main/templates/scaffolding/ScaffoldedController.groovy
      | Template installation complete
      
      I want to change mainly the gsp files generated.
      
      I've had this before long ago and found a solution, but can't
      remember what it was.  Any idea?
      
      Thanks for your quick response that led to the solution. 
      
      Regards,
      
      Chris 
      On 04/02/16 11:10, Burt Beckwith wrote:
    
    
      It's complaining about errorCode=404, location=/error
        - did you remove the url mapping for code 404 ("404"(view:'/notFound')
        ?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    
    -- 
Chris Malan
antoniecmalan@gmail.com
Try to relax and enjoy the crisis.
		-- Ashleigh Brilliant

**Comment by jblamber** [comment]
Hi there- this is my URLmappings:

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }
        
        "/lock"(view:"/login/lock")
        "/login"(view:"/login/auth")
        "/register"(view:"/login/register")

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
        "403"(view:'/auth/denied')
    }
}

But I can't believe I didnt make the connection between the 404 and the error. So what was happening was that I had a bootstrap css file that was referencing some fonts. I had allowed the font path in my static rules:

grails.plugin.springsecurity.controllerAnnotations.staticRules = [
...
[pattern: '/error',                 access: ['permitAll']],
...
[pattern: '/**/fonts/**', 			access: ['permitAll']],
...
]

But I didnt realize my font files werent actually in my app, so would give a legitmate 404. But in grails attempting to render the 404 page - it was throwing the spring security error. Fixing the 404 , by correctly moving the fonts to the right lcoation removed the exception and stacktrace - but this makes me think that any "legitimate" 404 page that is permitted by a static rule with throw this stack trace?

**Comment by jblamber** [comment]
I can reproduce this pretty easily - just have a path in your static rules that allows "permit-all" - but actually results in a 404. e.g:

grails.plugin.springsecurity.controllerAnnotations.staticRules = [
...
[pattern: '/foo', 					access: ['permitAll']],
...
]

Then make a call to /foo via curl/browser, and spring security will post the above exception.

**Comment by burtbeckwith** [comment]
@chrismalan that's a bug in the scaffolding plugin - you should report an issue in that project. Looking at the [source of the command](https://github.com/grails3-plugins/scaffolding/blob/master/src%2Fmain%2Fscripts%2FInstallTemplates.groovy) it's expecting that the GSPs are under `src/main/templates/scaffolding` like the Groovy templates are, but they're not in the plugin at all. I assume those are coming from the https://github.com/grails3-plugins/fields plugin but the files aren't getting copied from there.

**Comment by chrismalan** [comment]
Hi Burt,
      
      Thanks for this.  The code at
      https://github.com/grails3-plugins/scaffolding/tree/master/src/main/templates/scaffolding
      shows only the three files that get installed in the master
      branch.  The gsp files are in the bintray branch and much older. 
      Nothing in the fields plugin code.
      
      On 05/02/16 06:09, Burt Beckwith wrote:
    
    
      @chrismalan that's a bug in the
        scaffolding plugin - you should report an issue in that project.
        Looking at the source
          of the command it's expecting that the GSPs are under src/main/templates/scaffolding
        like the Groovy templates are, but they're not in the plugin at
        all. I assume those are coming from the https://github.com/grails3-plugins/fields
        plugin but the files aren't getting copied from there.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    
    -- 
Chris Malan
antoniecmalan@gmail.com
Afternoon very favorable for romance.  Try a single person for a change.

**Comment by chrismalan** [comment]
About the "There was a problem retrieving the current GrailsWebRequest. This usually indicates a filter ordering issue (the 'springSecurityFilterChain' filter-mapping element must be positioned after the 'grailsWebRequest' element when using @Secured annotations)."  This happens in a brand new project as soon as Spring Security Core has been installed and not a thing done to change the project at all.  It happens sometimes, sometimes it doesn't.  Obviously, it has to do with Spring Security Core and not something the programmer did or didn't do.

**Comment by jblamber** [comment]
I have an update witha work around. It seems the root cause of this issue is from this related issue: https://jira.grails.org/browse/GPSPRINGSECURITYCORE-253 - What is happening is that when you hit an unauthorized or missing page that is covered by the rules defined by grails.plugin.springsecurity.controllerAnnotations.staticRules = [ .. ] spring security is routing directly to the tomcat error pages rather than the correct grails pages IF your error pages are using any sort of grails layout.

Work around:
To force the correct routing, you need to update your url mappings to use a controller, and not just a view:

`
"400"(controller: "error", action: "invalid")
"500"(controller: "error", action: "denied")
"403"(controller: "error", action: "denied")
"404"(controller: "error", action: "notFound")`

and have a basic controller like so:

`class ErrorController {

    def error() {
        render view: 'error'
    }

    def invalid() {
        render view: 'error'
    }

    def denied() {
        render view: 'denied'
    }

    def notFound() {
        render view: 'notFound'
    }
}`

And additionally in your application.groovy set:

`grails.plugin.springsecurity.adh.errorPage = null`

**Comment by chrismalan** [comment]
Jason,
      
      Thanks for this.  I now have very nice error pages.  However, when
      starting up I still get these two errors:
      ERROR
      org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet]
      - Servlet.service() for servlet grailsDispatcherServlet threw
      exception
      java.lang.IllegalStateException: There was a problem retrieving
      the current GrailsWebRequest. This usually indicates a filter
      ordering issue (the 'springSecurityFilterChain' filter-mapping
      element must be positioned after the 'grailsWebRequest' element
      when using @Secured annotations).
      and
      ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]
      - Exception Processing ErrorPage[errorCode=404, location=/error]
      java.lang.IllegalStateException: There was a problem retrieving
      the current GrailsWebRequest. This usually indicates a filter
      ordering issue (the 'springSecurityFilterChain' filter-mapping
      element must be positioned after the 'grailsWebRequest' element
      when using @Secured annotations).
      
      
      They don't happen later on and has no influence on the
      application.
      
      With no web.xml I don't know how to order these two filters
      correctly.  The location=/error shouldn't happen as
      grails.plugin.springsecurity.adh.errorPage = null is in
      application.groovy.  Oh, yes, I also removed the renders from the
      error controller.
      
      Chris Malan
      
      On 17/02/16 14:52, Jason Lambert wrote:
    
    
      I have an update witha work around. It seems the root cause of
        this issue is from this related issue: https://jira.grails.org/browse/GPSPRINGSECURITYCORE-253
        - What is happening is that when you hit an unauthorized or
        missing page that is covered by the rules defined by
        grails.plugin.springsecurity.controllerAnnotations.staticRules =
        [ .. ] spring security is routing directly to the tomcat error
        pages rather than the correct grails pages IF your error pages
        are using any sort of grails layout.
      Work around:
        To force the correct routing, you need to update your url
        mappings to use a controller, and not just a view:
      
          "400"(controller: "error", action: "invalid")
          "500"(controller: "error", action: "denied")
          "403"(controller: "error", action: "denied")
          "404"(controller: "error", action: "notFound")
      and have a basic controller like so:
      `class ErrorController {
      def error() {
    render view: 'error'
}

def invalid() {
    render view: 'error'
}

def denied() {
    render view: 'denied'
}

def notFound() {
    render view: 'notFound'
}

      }`
      And additionally in your application.groovy set:
      grails.plugin.springsecurity.adh.errorPage = null
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    
    -- 
Chris Malan
antoniecmalan@gmail.com
Don't you wish you had more energy... or less ambition?

**Comment by burtbeckwith** [comment]
Fixed in v3.0.4

**Comment by yolobe** [comment]
Thanks! Checked and my issues are all resolved.

**Comment by jblamber** [comment]
Worked like a treat. I'm not seeing the exception anymore. Appreciate your work.
