### ISSUE TITLE
3.1.6 app fails to start after upgrade to version spring-security-core:3.1.0

### ISSUE THREAD

**Issue by hakanernam** [grails-plugins/grails-spring-security-core#428]
It looks  to be  due to a typo:

https://github.com/grails-plugins/grails-spring-security-core/commit/b318903dba66bf7e413f5554c85ed73b8a1be3fd#diff-bdb3d391c386ab6c06e337b138f20c66R952

```
	... 48 common frames omitted
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'secureKeyword' of bean class [org.springframework.security.web.access.channel.InsecureChannelProcessor]: Bean property 'secureKeyword' is not writable or has an invalid setter method. Did you mean 'insecureKeyword'?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:231)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:423)
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:280)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1514)
	... 56 common frames omitted
```

**Comment by burtbeckwith** [comment]
Fixed in v3.1.1
