### ISSUE TITLE
Controller forward does not seem to work with grails 3.1.X and spring-security-core:3.1.1

### ISSUE THREAD

**Issue by runwolf** [grails-plugins/grails-spring-security-core#444]
Trying to do a forward in a controller to another controller  fails 

with this code:
`forward(controller: "error", params: [title: "Sorry",message: "There is an error"])`

gives:

```
Unable to establish controller name to dispatch for [org.grails.web.mapping.RegexUrlMapping$1@32648142]. Dynamic closure
 invocation returned null. Check your mapping file is correct, when assigning the controller name as a request parameter
 it cannot be an optional token!. Stacktrace follows:
grails.web.mapping.exceptions.UrlMappingException: Unable to establish controller name to dispatch for [org.grails.web.m
apping.RegexUrlMapping$1@32648142]. Dynamic closure invocation returned null. Check your mapping file is correct, when a
ssigning the controller name as a request parameter it cannot be an optional token!
        at grails.artefact.Interceptor$Trait$Helper.doesMatch(Interceptor.groovy:97)
        at grails.artefact.Interceptor$Trait$Helper.doesMatch(Interceptor.groovy:69)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestC
ontextHolderExceptionTranslationFilter.groovy:64)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthentic
ationFilter.groovy:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groov
y:62)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at grails.plugin.springsecurity.web.filter.DebugFilter.doFilter(DebugFilter.groovy:72)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:193)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at grails.artefact.controller.support.RequestForwarder$Trait$Helper.forward(RequestForwarder.groovy:111)
        at com.la.PublicEventController$$EPsqmRW5.index(PublicEventController.groovy:39)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestC
ontextHolderExceptionTranslationFilter.groovy:64)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthentic
ationFilter.groovy:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groov
y:62)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at grails.plugin.springsecurity.web.filter.DebugFilter.invokeWithWrappedRequest(DebugFilter.groovy:102)
        at grails.plugin.springsecurity.web.filter.DebugFilter.doFilter(DebugFilter.groovy:69)
        at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestC
ontextHolderExceptionTranslationFilter.groovy:64)
        at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthentic
ationFilter.groovy:53)
        at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groov
y:62)
        at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

if I do a redirect it works:
`redirect(controller: "error", params: [title: "Sorry",message: "There is an error"])`

**Comment by snimavat** [comment]
This is not a spring security plugin issue.. @runwolf

**Comment by ddelponte** [comment]
@runwolf I would like to label this as "Not a Bug" and close it.  Do you have any objections?

**Comment by puneetbehl** [comment]
@ddelponte I am pretty sure that it's "not a bug". I think we should close this issue.

**Comment by ddelponte** [comment]
Marked as "not a bug" and closed
