### ISSUE TITLE
Infinite loop when uploading file too large using InterceptUrlMap and error controller

### ISSUE THREAD

**Issue by warwren** [grails-plugins/grails-spring-security-core#453]
**Steps to reproduce**
1. Create new application and add spring security core.
2. Use InterceptUrlMap as the securityConfigType.
3. Create an ErrorsController with views and edit UrlMappings 500 and 404 errors to use it.
4. Create a controller/view for uploading a file.
5. Add the errors controller and upload controller to the interceptUrlMap with permitAll.
6. Upload a file larger than the maximum (128k by default).

**Expected result:**
Get the 500 error page with the multipart exception indicating that the file was too large.

**Actual result:**
Request never completes with an infinite loop constantly hitting the multipart exception.

**Additional details**
Using controllerAnnotation.staticRules instead of interceptUrlMap seems to work properly.

Link to example of the problem:
https://github.com/warwren/exceptionLoop.git

**Comment by ddelponte** [comment]
Thanks @warwren for creating this issue and attaching a sample app.  Much appreciated 😄 

I think the sample app, however, is incomplete.  In it's current format, it does not support the uploading of files.  As a result, I'm unable to reproduce the problem.

Would you have time to update the `exceptionLoop` app so that it is able to demo the problem?

Thanks! ✨

**Comment by warwren** [comment]
Thanks for taking a look. It works fine for me, but perhaps it is not obvious which one of the links to use in the default grails page. It is the exceptionLoop.UploadController link which is http://localhost:8080/upload/index page. I hope that helps.

Cheers.

**Comment by ddelponte** [comment]
@warwren are you sure the attached code is correct?

I use the URL as specified and, after attempting to upload an image, I receive a 404 because the `upload/save` path doesn't exist.  That's what I would expect to happen.

**Comment by warwren** [comment]
I see what you mean. Your image must have been smaller than 128k maybe? If the file is too big, it won't even get to the 404 which is what I see. I have added an actual save action with a log message suggesting uploading a file bigger than 128k so you shouldn't get a 404 anymore.

**Comment by ddelponte** [comment]
I'm able to reproduce the problem.  Here's the error:

```
ERROR org.grails.web.errors.GrailsExceptionResolver - SizeLimitExceededException occurred when processing request: [POST] /upload/save
the request was rejected because its size (2770614) exceeds the configured maximum (128000). Stacktrace follows:
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (2770614) exceeds the configured maximum (128000)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:111)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:85)
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:76)
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1099)
	at org.grails.web.servlet.mvc.GrailsDispatcherServlet.checkMultipart(GrailsDispatcherServlet.groovy:72)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:932)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (2770614) exceeds the configured maximum (128000)
	at org.grails.web.filters.HiddenHttpMethodFilter.getHttpMethodOverride(HiddenHttpMethodFilter.java:71)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:60)
	... 3 common frames omitted
Caused by: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (2770614) exceeds the configured maximum (128000)
	... 5 common frames omitted
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (2770614) exceeds the configured maximum (128000)] with root cause
org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (2770614) exceeds the configured maximum (128000)
	at org.grails.web.filters.HiddenHttpMethodFilter.getHttpMethodOverride(HiddenHttpMethodFilter.java:71)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ddelponte** [comment]
It looks like this issue was first reported back in October of 2015 and has been determined to not be a bug in Grails.

Read more at https://github.com/grails/grails-core/issues/9378

If you are deploying with Tomcat, you have to configure maxSwallowSize.

This is how you do it in a Grails/Spring Boot application: http://stackoverflow.com/questions/32250030/setting-a-tomcat-property-using-spring-boot-application-properties

Are you okay with me closing this issue?

**Comment by warwren** [comment]
Yes, I'm fine with you closing this issue. Thanks.
