### ISSUE TITLE
java.lang.IllegalArgumentException randomly thrown in production mode

### ISSUE THREAD

**Issue by antondelpiero** [grails-plugins/grails-spring-security-core#533]
**Grails: 2.5.5
grails-spring-security-core: 2.0.0**

I'm getting java.lang.IllegalArgumentException only in my production mode. 
Here is my error log:
`java.lang.IllegalArgumentException: Cannot pass null or empty values to constructor
    at grails.plugin.springsecurity.userdetails.GrailsUser.<init>(GrailsUser.java:52)
    at grails.plugin.springsecurity.userdetails.GormUserDetailsService.createUserDetails(GormUserDetailsService.groovy:122)
    at grails.plugin.springsecurity.userdetails.GormUserDetailsService.$tt__loadUserByUsername(GormUserDetailsService.groovy:67)
    at grails.plugin.springsecurity.userdetails.GormUserDetailsService.loadUserByUsername(GormUserDetailsService.groovy:71)
    at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.java:59)
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
    at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
org.springframework.security.authentication.InternalAuthenticationServiceException: Cannot pass null or empty values to constructor
    at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.java:59)
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
    at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.java:59)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`

The problem is the exception is not always reproducible but can't be just ignored since we getting it like one or two every two or three days

**Comment by sdelamo** [comment]
We will need a sample app with a reproducible example.

**Comment by antondelpiero** [comment]
Hi @sdelamo, thx for replying, but the problem is I don't have any reproducible example as it is not always happens. 

Maybe you can give me a hint, this was called before getting the error `https://<my_url>/j_spring_security_check`
