### ISSUE TITLE
BadCredentialsException: Bad credentials except the credentials are correct

### ISSUE THREAD

**Issue by anti43** [grails-plugins/grails-spring-security-core#594]
### Steps to Reproduce

1. Create new Grails 4 app with application forge
2. Add dependency 'org.grails.plugins:spring-security-core:4.0.0.RC2'
3. Run s2-quickstart 

`s2-quickstart your.package User Role`

4. Create user in bootstrap

```
                def adminRole = new Role(authority: 'ROLE_ADMIN').save(flush: true)
                def aUser = new User(username: 'admin', enabled: true, password: 'apassword')
                aUser.save(flush: true)
                UserRole.create aUser, adminRole, true
```
5. Start app. Try login with admin, apassword

### Expected Behaviour

Login should work

### Actual Behaviour

Login fails

2019-09-05 11:25:18.927 DEBUG --- [nio-8080-exec-2] o.s.s.a.dao.DaoAuthenticationProvider    : Authentication failed: password does not match stored value
2019-09-05 11:25:18.929 DEBUG --- [nio-8080-exec-2] ailsUsernamePasswordAuthenticationFilter : Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials

### Environment Information

- **Operating System**: Windows 10 
- **GORM Version:** 7.0.2.RELEASE
- **Grails Version (if using Grails):** 4.0.0
- **JDK Version:** 1.8

### Stack

```
org.springframework.security.authentication.BadCredentialsException: Bad credentials
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:93)
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:166)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
	at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
	at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.groovy:53)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
```

**Comment by anti43** [comment]
Can be closed. For some reason there was no UserPasswordEncoderListener registered?
