### ISSUE TITLE
ClassCastException on logout MutableLogoutFilter.java:69

### ISSUE THREAD

**Issue by jrAtAustin** [grails-plugins/grails-spring-security-core#625]
I have a Grails 2.5.6 App using Spring Security Core, Spring Security SAML,... After login to Azure AD when I logout I get a ClassCastException on MutableLogoutFilter.java:69 for class org.springframework.security.web.authentication.logout.SimpleUrlLogoutSuccessHandler from spring-security-web-3.2.9.RELEASE.jar. MutableLogoutFilter.doFilter(...) is iterating **handlers** as class LogoutHandler and SimpleUrlLogoutSuccessHandler does not implement the LogoutHandler interface. MutableLogoutFilter.java is from this plugin spring-security-core-2.0.0. See MutableLogoutFilter.doFilter(...) source code below.

```
	@Override
	public void doFilter(final ServletRequest req, final ServletResponse res, final FilterChain chain)
			throws IOException, ServletException {

		HttpServletRequest request = (HttpServletRequest) req;
		HttpServletResponse response = (HttpServletResponse) res;

		if (!requiresLogout(request, response)) {
			chain.doFilter(request, response);
			return;
		}

		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		log.debug("Logging out user '{}' and transferring to logout destination", auth);

		// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Exception occurs here !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		for (LogoutHandler handler : handlers) {
			handler.logout(request, response, auth);
		}

		logoutSuccessHandler.onLogoutSuccess(request, response, auth);
	}
```

### Steps to Reproduce

1. Login to app using SAML SSO
2. Logout app

### Expected Behaviour

Successful logout and session cleanup.

### Actual Behaviour

App throws exception and browser shows a blank page and is unresponsive. I can login and logout fails.

### Environment Information

- **Operating System**: macOS Catilina Version 10.15.5
- **GORM Version:** 3.1.4
- **Grails Version (if using Grails):** 2.5.6
- **JDK Version:** 1.8.0_232

### Stacktrace

```
java.lang.ClassCastException: org.springframework.security.web.authentication.logout.SimpleUrlLogoutSuccessHandler cannot be cast to org.springframework.security.web.authentication.logout.LogoutHandler
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:69)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.saml.SAMLLogoutProcessingFilter.processLogout(SAMLLogoutProcessingFilter.java:206)
	at org.springframework.security.saml.SAMLLogoutProcessingFilter.doFilter(SAMLLogoutProcessingFilter.java:104)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.saml.SAMLLogoutFilter.processLogout(SAMLLogoutFilter.java:164)
	at org.springframework.security.saml.SAMLLogoutFilter.doFilter(SAMLLogoutFilter.java:106)
```

### BuildConfig.groovy dependencies and plugins:

```
    dependencies {

        build 'org.apache.httpcomponents:httpcore:4.4.6'
        build 'org.apache.httpcomponents:httpclient:4.5.3'
        runtime 'org.apache.httpcomponents:httpcore:4.4.6'
        runtime 'org.apache.httpcomponents:httpclient:4.5.3'

        runtime "org.postgresql:postgresql:42.2.6"
        runtime "rhino:js:1.7R2"
        runtime "com.github.jknack:handlebars:1.0.0"
        runtime "org.grails:grails-web-databinding-spring:2.4.4"

        compile "org.codehaus.groovy.modules.http-builder:http-builder:0.6"
        compile 'commons-beanutils:commons-beanutils:1.8.3'

        compile 'com.twilio.sdk:twilio-java-sdk:5.8.0', {
            excludes('jackson-core-asl', 'jackson-mapper-asl','jackson-databind', 'jackson-annotations')
        }

        compile 'org.jolokia:jolokia-core:1.3.5'

        compile 'com.fasterxml.jackson.core:jackson-core:2.8.5'
        compile 'com.smartystreets.api:smartystreets-java-sdk:1.0.7'
        compile 'com.getsentry.raven:raven:7.8.2'
        compile 'com.google.guava:guava:23.0-android'
        compile( "commons-validator:commons-validator:1.4.1" ) {
            excludes 'xml-apis','commons-digester','commons-logging','commons-beanutils', 'commons-collections'
        }

        compile 'com.github.ua-parser:uap-java:1.4.3'
        runtime 'com.bertramlabs.plugins:asset-pipeline-core:2.15.1'

        // SAML 2.x support for the Spring Security Plugin
        // http://sphoortia.github.io/grails-spring-security-saml/docs/guide/usage.html
        compile ("org.springframework.security.extensions:spring-security-saml2-core:1.0.1.RELEASE") {
            export = false
            excludes 'joda-time:joda-time:1.6.2'
        }
        compile('org.springframework.security:spring-security-core:3.2.9.RELEASE')
        compile('org.springframework.security:spring-security-web:3.2.9.RELEASE')
        compile('joda-time:joda-time:2.8.1')
    }

    plugins {

        compile ':cache:1.1.8'
        compile "org.grails.plugins:webxml:1.4.1"
        compile ":spring-security-core:2.0.0"

        // SAML 2.x support for the Spring Security Plugin
        // http://sphoortia.github.io/grails-spring-security-saml/docs/guide/usage.html
        compile ":spring-security-saml:2.0.0"

        compile ":jquery-ui:1.10.4"
        compile ":build-test-data:2.4.0"
        compile ":fixtures:1.3"
        compile ":codenarc:0.18"
        compile ":mail:1.0.7", {
            excludes 'spring-test'
        }

        compile ':scaffolding:2.1.2'
        compile ":jmx:0.9"

        compile "org.grails.plugins:postgresql-extensions:4.6.1"

        build(":release:3.1.1",
            ":rest-client-builder:2.1.1") {
            export = false
        }
        build ':tomcat:8.0.33'

        runtime ':hibernate4:4.3.8.1'

        runtime ":jquery:1.11.1"

        compile "org.grails.plugins:asset-pipeline:2.14.1.1", {
            excludes 'asset-pipeline-core:2.14.1'
        }

        compile "org.grails.plugins:less-asset-pipeline:2.14.1"

        runtime ":fields:1.3"
        runtime ":xframeoptions:1.0"

        compile ":remote-control:2.0"
        compile ":export:1.6"
        compile "org.grails.plugins:wkhtmltopdf:0.1.10"

        runtime ":cache-headers:1.1.7"

        runtime ':aws-sdk:1.11.11'
   }
```

### Example Application

- TODO: link to Github repository with example that reproduces the issue

**Comment by jrAtAustin** [comment]
Got past this by changing bean configuration. Not certain which configuration fixed the problem. I formatted my IDP.xml file and that seem to have contributed to the issues I was encountering.
